grpc:
  methodConfig:
    - name:
        - service: RaftService
      retryPolicy:
        MaxAttempts: 2
        InitialBackoff: ".01s"
        MaxBackoff: ".01s"
        BackoffMultiplier: 1.0
        RetryableStatusCodes:
          - UNAVAILABLE
          - INTERNAL
          - ABORTED
          - DEADLINE_EXCEEDED
          - RESOURCE_EXHAUSTED
  retryThrottling:
    maxTokens: 100
    tokenRatio: 0.1

membership:
  current_node_id: node1
  current_port: 18081
  current_node_addr: localhost:18081
  cluster_size: 3
  all_members:
    - node_id: node1
      node_uri: localhost:18081
    - node_id: node2
      node_uri: localhost:18082
    - node_id: node3
      node_uri: localhost:18083